import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin', 'cyrillic'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="header">
          <h1>
            <Link href={'/'}>ARMAGEDDON 2023</Link>
          </h1>
          <>
            <p>{`ООО "Команда им Б. Уиллиса"`}</p>
            <p>Взрываем астероиды с 1988 года.</p>
          </>
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
